# Generated by Django 4.0.1 on 2022-12-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outbreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite', models.TextField(default=None)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('date', models.DateField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
        migrations.AddIndex(
            model_name='outbreak',
            index=models.Index(fields=['latitude', 'longitude', 'date'], name='app_outbrea_latitud_0e29fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='outbreak',
            unique_together={('latitude', 'longitude', 'date')},
        ),
    ]
